config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'validation_jobs/getjob/:id', to: 'validation_jobs#getjob'

  resources :validation_jobs, except: [:edit]

  get 'deploys/getinput/:id', to: 'deploys#getinput'

  resources :deploys, except: [:edit]

  resources :groups

  resources :accounts

  resources :permissions

  resources :roles

  resources :users

  get 'home/login'

  post 'home/login'

  get 'home/logout'

  get 'home/dashboard'

  get 'home/messages'

  get 'home/alerts'

  get 'home/tasks'

  delete 'home/account/deleteuser/:id', to: 'home#deleteuser' 

  post 'home/account/adduser', to: 'home#adduser'

  get 'home/account/:id', to: 'home#changeaccount'
  
  get 'home/account'
  
  get 'home/user'

  resources :environments, except: [:edit]

  get 'tasks/taskform'

  resources :tasks, except: [:edit]

  post 'workflows/addtask', to: 'workflows#addtask'
  
  delete 'workflows/deltask', to: 'workflows#deltask'

  post 'workflows/step/completed', to: 'workflows#addoncompleted'

  delete 'workflows/step/completed', to: 'workflows#removeoncompleted'

  post 'workflows/step/success', to: 'workflows#addonsuccess'

  delete 'workflows/step/success', to: 'workflows#removeonsuccess'

  post 'workflows/step/failure', to: 'workflows#addonfailure'

  delete 'workflows/step/failure', to: 'workflows#removeonfailure'

  put 'workflows/:id/reload', to: 'workflows#reload'

  get 'workflows/:id/diagram', to: 'workflows#diagram'

  resources :workflows, except: [:edit]

  resources :scripts, except: [:edit]

  resources :checks, except: [:edit]

  resources :dashboards, except: [:edit]

  resources :replicas, except: [:edit]

get 'projects/tablelist', to: 'projects#tablelist'

  resources :projects, except: [:edit]

  resources :repositories, except: [:edit]

get 'ciworkers/tablelist', to: 'ciworkers#tablelist'

  resources :ciworkers, except: [:edit]

get 'cistacks/tablelist', to: 'cistacks#tablelist'

get 'cistacks/:id/manage', to: 'cistacks#manage'

post 'cistacks/:id/manage', to: 'cistacks#manage'

  resources :cistacks, except: [:edit]

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  # Requirements
  require 'connector'
  require 'securerandom'
  # Model relationships
  belongs_to :account  
  # Validations
  validates :name, presence: true
  before_create :assignUuid
  after_create :createMsg
  before_destroy :deleteMsg
  # Filters
  # Attributes


  def assignUuid
    self.uuid = SecureRandom.hex(20)
  end

  def createMsg
    msg = {}
    msg[:function] = "createRepository"
    msg[:id] = self.uuid
    msg[:name] = self.name
    msg[:repositorytype] = self.repotype
    logger.debug(Connector.broadcast('continuous-repo','continuous-repo',msg))
  end

  def deleteMsg
    msg = {}
    msg[:function] = "deleteRepository"
    msg[:id] = self.uuid
    msg[:name] = self.name
    msg[:repositorytype] = self.repotype
    logger.debug(Connector.broadcast('continuous-repo','continuous-repo',msg))
  end

  def updateMsg
    msg = {}
    msg[:function] = "updateRepository"
    msg[:id] = self.uuid
    msg[:name] = self.name
    logger.debug(Connector.broadcast('continuous-repo','continuous-repo',msg))
  end

  def sendDestroy
    deleteMsg
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]
  before_action :checkOwner, only: [:show, :edit, :update, :destroy]
  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = @current_account.repositories.all
    @repository = Repository.new
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        @current_account.repositories << @repository
        format.html { redirect_to "/repositories", notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { redirect_to "/deploys", notice: "Error while creating the resource" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    #@repository.sendDestroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:name, :repotype)
    end

    def checkOwner
      checkObjectOwner("repositories", @repository)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/_form_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Create
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
<%= form_for(@repository, html: {role: "form"}) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Create New Package Repository</h4>
      </div>
      <div class="modal-body">

  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :repository_type %><br>
    <%= select_tag("repository[repotype]", options_for_select([['apt','apt'],['yum','yum'],['web','web']], @repository.repotype), {:multiple => false, :prompt => 'Select Repository Type', :class => "form-control" } ) %>
  </div>



      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Create', :class => "btn btn-primary" %>
      </div>
    </div>
      <% end %>
  </div>
</div>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.name %></td>
        <td><%= link_to 'Show', repository %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'form_modal' %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>
<p>
  <strong>Type:</strong>
  <%= @repository.repotype %>
</p>
<p>
  <strong>URL:</strong>
  <a href="http://<%= #{Continuous::Application.config.repositoryserver} %>/<%= @repository.name %>">http://<%= #{Continuous::Application.config.repositoryserver} %>/<%= @repository.name %></a>
</p>
<%= link_to 'Back', repositories_path %>