config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'validation_jobs/getjob/:id', to: 'validation_jobs#getjob'

  resources :validation_jobs, except: [:edit]

  get 'deploys/getinput/:id', to: 'deploys#getinput'

  resources :deploys, except: [:edit]

  resources :groups

  resources :accounts

  resources :permissions

  resources :roles

  resources :users

  get 'home/login'

  post 'home/login'

  get 'home/logout'

  get 'home/dashboard'

  get 'home/messages'

  get 'home/alerts'

  get 'home/tasks'

  delete 'home/account/deleteuser/:id', to: 'home#deleteuser' 

  post 'home/account/adduser', to: 'home#adduser'

  get 'home/account/:id', to: 'home#changeaccount'
  
  get 'home/account'
  
  get 'home/user'

  resources :environments, except: [:edit]

  get 'tasks/taskform'

  resources :tasks, except: [:edit]

  post 'workflows/addtask', to: 'workflows#addtask'
  
  delete 'workflows/deltask', to: 'workflows#deltask'

  post 'workflows/step/completed', to: 'workflows#addoncompleted'

  delete 'workflows/step/completed', to: 'workflows#removeoncompleted'

  post 'workflows/step/success', to: 'workflows#addonsuccess'

  delete 'workflows/step/success', to: 'workflows#removeonsuccess'

  post 'workflows/step/failure', to: 'workflows#addonfailure'

  delete 'workflows/step/failure', to: 'workflows#removeonfailure'

  put 'workflows/:id/reload', to: 'workflows#reload'

  get 'workflows/:id/diagram', to: 'workflows#diagram'

  resources :workflows, except: [:edit]

  resources :scripts, except: [:edit]

  resources :checks, except: [:edit]

  resources :dashboards, except: [:edit]

  resources :replicas, except: [:edit]

get 'projects/tablelist', to: 'projects#tablelist'

  resources :projects, except: [:edit]

  resources :repositories, except: [:edit]

get 'ciworkers/tablelist', to: 'ciworkers#tablelist'

  resources :ciworkers, except: [:edit]

get 'cistacks/tablelist', to: 'cistacks#tablelist'

get 'cistacks/:id/manage', to: 'cistacks#manage'

post 'cistacks/:id/manage', to: 'cistacks#manage'

  resources :cistacks, except: [:edit]

end

app/models/group.rb
class Group < ActiveRecord::Base
  # Requirements
  # Model relationships
  has_and_belongs_to_many :users
  belongs_to :account
  # Validations
  # Filters
  # Attributes
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { redirect_to "/deploys", notice: "Error while creating the resource" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:uuid, :name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.uuid %></td>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @group.uuid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>