config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'validation_jobs/getjob/:id', to: 'validation_jobs#getjob'

  resources :validation_jobs, except: [:edit]

  get 'deploys/getinput/:id', to: 'deploys#getinput'

  resources :deploys, except: [:edit]

  resources :groups

  resources :accounts

  resources :permissions

  resources :roles

  resources :users

  get 'home/login'

  post 'home/login'

  get 'home/logout'

  get 'home/dashboard'

  get 'home/messages'

  get 'home/alerts'

  get 'home/tasks'

  delete 'home/account/deleteuser/:id', to: 'home#deleteuser' 

  post 'home/account/adduser', to: 'home#adduser'

  get 'home/account/:id', to: 'home#changeaccount'
  
  get 'home/account'
  
  get 'home/user'

  resources :environments, except: [:edit]

  get 'tasks/taskform'

  resources :tasks, except: [:edit]

  post 'workflows/addtask', to: 'workflows#addtask'
  
  delete 'workflows/deltask', to: 'workflows#deltask'

  post 'workflows/step/completed', to: 'workflows#addoncompleted'

  delete 'workflows/step/completed', to: 'workflows#removeoncompleted'

  post 'workflows/step/success', to: 'workflows#addonsuccess'

  delete 'workflows/step/success', to: 'workflows#removeonsuccess'

  post 'workflows/step/failure', to: 'workflows#addonfailure'

  delete 'workflows/step/failure', to: 'workflows#removeonfailure'

  put 'workflows/:id/reload', to: 'workflows#reload'

  get 'workflows/:id/diagram', to: 'workflows#diagram'

  resources :workflows, except: [:edit]

  resources :scripts, except: [:edit]

  resources :checks, except: [:edit]

  resources :dashboards, except: [:edit]

  resources :replicas, except: [:edit]

get 'projects/tablelist', to: 'projects#tablelist'

  resources :projects, except: [:edit]

  resources :repositories, except: [:edit]

get 'ciworkers/tablelist', to: 'ciworkers#tablelist'

  resources :ciworkers, except: [:edit]

get 'cistacks/tablelist', to: 'cistacks#tablelist'

get 'cistacks/:id/manage', to: 'cistacks#manage'

post 'cistacks/:id/manage', to: 'cistacks#manage'

  resources :cistacks, except: [:edit]

end

app/models/ciworker.rb
class Ciworker < ActiveRecord::Base
  # Requirements
  require 'connector'
  require 'securerandom'
  # Model Relationships
  belongs_to :cistack
  belongs_to :account  
  # Validations
  validates :name, :image, :flavor, presence: true
  before_create :assignUuid
  after_create :createMsg
  before_destroy :deleteMsg
  # Filters
  # Attributes


  def assignUuid
    self.uuid = SecureRandom.hex(20)
    self.status = "Cloud - CI Worker requested"
  end

  def createMsg
    msg = {}
    msg[:function] = "createCiWorker"
    msg[:ciworkeruuid] = self.uuid
    msg[:name] = self.name
    msg[:flavor] = self.flavor
    msg[:image] = self.image
    msg[:cistackuuid] = Cistack.find(self.cistack_id).uuid
    logger.debug(Connector.publish('continuous-ci','provision',msg))
  end

  def deleteMsg
    msg = {}
    msg[:function] = "deleteCiWorker"
    msg[:ciworkeruuid] = self.uuid
    msg[:name] = self.name
    msg[:cistackuuid] = Cistack.find(self.cistack_id).uuid
    logger.debug(Connector.publish('continuous-ci','provision',msg))
  end

  def updateMsg
    msg = {}
    msg[:function] = "updateCiWorker"
    msg[:ciworkeruuid] = self.uuid
    msg[:name] = self.name
    logger.debug(Connector.publish('continuous-ci','provision',msg))
  end

  def sendDestroy
    deleteMsg
  end

end

app/controllers/ciworkers_controller.rb
class CiworkersController < ApplicationController
  before_action :set_ciworker, only: [:show, :edit, :update, :destroy]
  before_action :checkOwner, only: [:show, :edit, :update, :destroy]
  # GET /ciworkers
  # GET /ciworkers.json
  def index
    @ciworkers = @current_account.ciworkers.all
    @ciworker = Ciworker.new
    @cistacks = @current_account.cistacks
  end

  # GET /ciworkers/1
  # GET /ciworkers/1.json
  def show
  end

  # GET /ciworkers/new
  def new
    @ciworker = Ciworker.new
    @cistacks = @current_account.cistacks
  end

  # GET /ciworkers/1/edit
  def edit
    @cistacks = @current_account.cistacks
  end

  # POST /ciworkers
  # POST /ciworkers.json
  def create
    @ciworker = Ciworker.new(ciworker_params)

    respond_to do |format|
      if @ciworker.save
        @current_account.ciworkers << @ciworker
        format.html { redirect_to "/ciworkers", notice: 'Ciworker was successfully created.' }
        format.json { render :show, status: :created, location: @ciworker }
      else
        format.html { redirect_to "/deploys", notice: "Error while creating the resource" }
        format.json { render json: @ciworker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ciworkers/1
  # PATCH/PUT /ciworkers/1.json
  def update
    respond_to do |format|
      if @ciworker.update(ciworker_params)
        format.html { redirect_to @ciworker, notice: 'Ciworker was successfully updated.' }
        format.json { render :show, status: :ok, location: @ciworker }
      else
        format.html { render :edit }
        format.json { render json: @ciworker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ciworkers/1
  # DELETE /ciworkers/1.json
  def destroy
    @ciworker.sendDestroy
    #@ciworker.destroy
    respond_to do |format|
      format.html { redirect_to ciworkers_url, notice: 'Ciworker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tablelist
    @ciworkers = @current_account.ciworkers.all
    render :partial => "tablelist", :locals => { :ciworkers => @ciworkers }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ciworker
      @ciworker = Ciworker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ciworker_params
      params.require(:ciworker).permit(:name, :image, :flavor, :cistack_id)
    end

    def checkOwner
      checkObjectOwner("ciworkers", @ciworker)
    end
end

app/helpers/ciworkers_helper.rb
module CiworkersHelper
end

app/views/ciworkers/_form.html.erb
<%= form_for(@ciworker) do |f| %>
  <% if @ciworker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciworker.errors.count, "error") %> prohibited this ciworker from being saved:</h2>

      <ul>
      <% @ciworker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :flavor %><br>
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :cistacks %><br>
    <%= select_tag("ciworker[cistack_id]", options_for_select(@cistacks.all.collect {|t| [t.name, t.id]}, @ciworker.cistack_id), {:multiple => false, :prompt => 'Select CiStack', :class => "form-control" } ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ciworkers/_form_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Create
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
<%= form_for(@ciworker, html: {role: "form"}) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Create New CI Worker</h4>
      </div>
      <div class="modal-body">

  <% if @ciworker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ciworker.errors.count, "error") %> prohibited this ciworker from being saved:</h2>

      <ul>
      <% @ciworker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= select_tag("ciworker[image]", options_for_select([['ubuntu','ubuntu'],['centos','centos'],['centos7','centos7'],['trusty','trusty'],['container','container']],@ciworker.image), {:multiple => false, :class => "form-control"} ) %>
  </div>
  <div class="form-group">
    <%= f.label :flavor %><br>
    <%= select_tag("ciworker[flavor]", options_for_select([['small',1022],['medium',2002]],@ciworker.flavor), {:multiple => false, :class => "form-control"} ) %>
  </div>
  <div class="form-group">
    <%= f.label :cistack %><br>
    <%= select_tag("ciworker[cistack_id]", options_for_select(@cistacks.all.collect {|t| [t.name, t.id]}, @ciworker.cistack_id), {:multiple => false, :class => "form-control" } ) %>
  </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Create', :class => "btn btn-primary" %>
      </div>
    </div>
      <% end %>
  </div>
</div>

app/views/ciworkers/_tablelist.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Status</th>
      <th>IP Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ciworkers.each do |ciworker| %>
      <tr>
        <td><%= ciworker.name %></td>
        <td><%= ciworker.image %></td>
        <td><%= ciworker.status %></td>
        <td><%= ciworker.privateip %></td>
        <td><%= link_to 'Show', ciworker %></td>
        <td><%= link_to 'Destroy', ciworker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ciworkers/edit.html.erb
<h1>Editing ciworker</h1>

<%= render 'form' %>

<%= link_to 'Show', @ciworker %> |
<%= link_to 'Back', ciworkers_path %>

app/views/ciworkers/index.html.erb
<h1>Listing ciworkers</h1>
<div id="ciworkertablelist">
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>IP</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ciworkers.each do |ciworker| %>
      <tr>
        <td><%= ciworker.name %></td>
        <td><%= ciworker.image %></td>
        <td><% if not ciworker.privateip.nil? %><%= ciworker.privateip %><% end %></td>
        <td><%= ciworker.status %></td>
        <td><%= link_to 'Show', ciworker %></td>
        <td><%= link_to 'Destroy', ciworker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= render 'form_modal' %>

app/views/ciworkers/new.html.erb
<h1>New ciworker</h1>

<%= render 'form' %>

<%= link_to 'Back', ciworkers_path %>

app/views/ciworkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ciworker.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @ciworker.image %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @ciworker.flavor %>
</p>

<%= link_to 'Back', ciworkers_path %>