config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'validation_jobs/getjob/:id', to: 'validation_jobs#getjob'

  resources :validation_jobs, except: [:edit]

  get 'deploys/getinput/:id', to: 'deploys#getinput'

  resources :deploys, except: [:edit]

  resources :groups

  resources :accounts

  resources :permissions

  resources :roles

  resources :users

  get 'home/login'

  post 'home/login'

  get 'home/logout'

  get 'home/dashboard'

  get 'home/messages'

  get 'home/alerts'

  get 'home/tasks'

  delete 'home/account/deleteuser/:id', to: 'home#deleteuser' 

  post 'home/account/adduser', to: 'home#adduser'

  get 'home/account/:id', to: 'home#changeaccount'
  
  get 'home/account'
  
  get 'home/user'

  resources :environments, except: [:edit]

  get 'tasks/taskform'

  resources :tasks, except: [:edit]

  post 'workflows/addtask', to: 'workflows#addtask'
  
  delete 'workflows/deltask', to: 'workflows#deltask'

  post 'workflows/step/completed', to: 'workflows#addoncompleted'

  delete 'workflows/step/completed', to: 'workflows#removeoncompleted'

  post 'workflows/step/success', to: 'workflows#addonsuccess'

  delete 'workflows/step/success', to: 'workflows#removeonsuccess'

  post 'workflows/step/failure', to: 'workflows#addonfailure'

  delete 'workflows/step/failure', to: 'workflows#removeonfailure'

  put 'workflows/:id/reload', to: 'workflows#reload'

  get 'workflows/:id/diagram', to: 'workflows#diagram'

  resources :workflows, except: [:edit]

  resources :scripts, except: [:edit]

  resources :checks, except: [:edit]

  resources :dashboards, except: [:edit]

  resources :replicas, except: [:edit]

get 'projects/tablelist', to: 'projects#tablelist'

  resources :projects, except: [:edit]

  resources :repositories, except: [:edit]

get 'ciworkers/tablelist', to: 'ciworkers#tablelist'

  resources :ciworkers, except: [:edit]

get 'cistacks/tablelist', to: 'cistacks#tablelist'

get 'cistacks/:id/manage', to: 'cistacks#manage'

post 'cistacks/:id/manage', to: 'cistacks#manage'

  resources :cistacks, except: [:edit]

end

app/models/image.rb
class Image < ActiveRecord::Base
  # Requirements
  require 'net/https'
  require 'securerandom'
  require 'json'
  require 'base64'
  # Model Relationships
  belongs_to :account
  # Validations
  validates :name, :imagetype, :description, :location, presence: true
  before_create :saveImageService
  before_destroy :destroyImageService
  # Filters
  # Attributes
    

  def queryImageService
    begin
      http = Net::HTTP.new(Continuous::Application.config.registryhost, 8080)
      http.use_ssl = true
      pass = Base64.encode64("#{Continuous::Application.config.registryuser}:#{Continuous::Application.config.registrypassword}")
      webpass = "Basic #{pass}"
      header = {'Authorization' => webpass, 'Authentication' => webpass, 'Content-type' => 'application/json' }
      response = http.get("/v1/_ping", header)
      if response.code.to_i == 200
        return true
      else
        return false
      end
    rescue
      logger.info("Error while querying the docker registry service")
      return false
    end
  end

  def saveImageService
    if queryImageService
    else
      return false
    end
  end

  def destroyImageService
    if queryImageService
    else
      return false
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :uuid, :imagetype, :location)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="field">
    <%= f.label :imagetype %><br>
    <%= f.text_field :imagetype %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Uuid</th>
      <th>Imagetype</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image.uuid %></td>
        <td><%= image.imagetype %></td>
        <td><%= image.location %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @image.uuid %>
</p>

<p>
  <strong>Imagetype:</strong>
  <%= @image.imagetype %>
</p>

<p>
  <strong>Location:</strong>
  <%= @image.location %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>